export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL';
export const GET_ARTICLE_BY_ID_START = 'GET_ARTICLE_BY_ID_START';
export const GET_ARTICLE_BY_ID_SUCCESS = 'GET_ARTICLE_BY_ID_SUCCESS';
export const GET_ARTICLE_BY_ID_FAIL = 'GET_ARTICLE_BY_ID_FAIL';
export const POST_ARTICLE_START = 'POST_ARTICLE_START';
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS';
export const POST_ARTICLE_FAIL = 'POST_ARTICLE_FAIL';

export const GET_TOPICS_START = 'GET_TOPICS_START';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAIL = 'GET_TOPICS_FAIL';

export const GET_ARTICLE_COMMENTS_START = 'GET_ARTICLE_COMMENTS_START';
export const GET_ARTICLE_COMMENTS_SUCCESS = 'GET_ARTICLE_COMMENTS_SUCCESS';
export const GET_ARTICLE_COMMENTS_FAIL = 'GET_ARTICLE_COMMENTS_FAIL';
export const POST_ARTICLE_COMMENTS_START = 'POST_ARTICLE_COMMENTS_START';
export const POST_ARTICLE_COMMENTS_SUCCESS = 'POST_ARTICLE_COMMENTS_SUCCESS';
export const POST_ARTICLE_COMMENTS_FAIL = 'POST_ARTICLE_COMMENTS_FAIL';
